server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redirige cualquier ruta al index.html para que React Router funcione sin rompernos
        try_files $uri $uri/ /index.html;
    }

    # Caché opcional para archivos estáticos de assets
    location /assets/ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}